baseurl: https://dorianb.net/blog
languageCode: en-us
theme:
    - custom
    - hugo-theme-stack
paginate: 10
title: Dorian B.

languages:
    en:
        languageName: English
        title: Dorian B.
        weight: 1
    fr:
        languageName: Français
        title: Dorian B.
        weight: 2
        disabled: true

# Change it to your Disqus shortname before using
disqusShortname: dorianb-blog

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: favicon.ico

    footer:
        since: 2022
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🐙
        compact: true
        subtitle: Understand, don't memorize.
        avatar:
            enabled: true
            local: false
            src: https://avatars.githubusercontent.com/u/20194872?s=400&u=985e4b2550b35686b0be0900b145e2740b235265&v=4

    article:
        headingAnchor: true
        math: true
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: giscus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/component.html
        waline:
            serverURL:
            lang:
            pageview:
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
            requiredMeta:
                - name
                - email
                - url
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo: DorianBDev/blog
            repoID: R_kgDOHqETOg
            category: Comments
            categoryID: DIC_kwDOHqETOs4Ci_rr
            mapping: pathname
            strict: 1
            lightTheme: noborder_light
            darkTheme: noborder_dark
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition: top
            lang: en

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: false

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    # main:
        # - identifier: website
        #   name: dorianb.net
        #   url: https://dorianb.net
        #   weight: 1000
        #   params:
        #     icon: arrow-back
        #     newTab: false

    # For more icons see https://tablericons.com/ and place in theme/custom/assets/icons
    social:
        - identifier: linkedin
          name: Linkedin
          url: https://www.linkedin.com/in/dorian-bachelot/
          weight: 1
          params:
            icon: brand-linkedin

        - identifier: github
          name: GitHub
          url: https://github.com/DorianBDev
          weight: 2
          params:
            icon: brand-github

        - identifier: gitlab
          name: Gitlab
          url: https://gitlab.com/DorianBDev
          weight: 3
          params:
            icon: brand-gitlab

        - identifier: twitter
          name: Twitter
          url: https://x.com/dorianbchlt
          weight: 4
          params:
            icon: brand-twitter

        - identifier: rootme
          name: RootMe
          url: https://www.root-me.org/dorianbdev
          weight: 5
          params:
            icon: brand-rootme

        - identifier: hackthebox
          name: Hack The Box
          url: https://app.hackthebox.com/profile/880964
          weight: 6
          params:
            icon: brand-htb

        - identifier: rss
          name: Rss Feed
          url: https://dorianb.net/blog/index.xml
          weight: 7
          params:
            icon: brand-rss


related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
        parser:
            attribute:
                block: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 1
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
